
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Dec 02 10:50:38 CET 2024
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 18;
  public static final int LS = 19;
  public static final int OR = 17;
  public static final int INT = 10;
  public static final int CHAR = 11;
  public static final int LOOP = 15;
  public static final int LE = 20;
  public static final int ID = 8;
  public static final int GR = 23;
  public static final int OBR = 3;
  public static final int ASS = 14;
  public static final int SEMIC = 7;
  public static final int COMMA = 9;
  public static final int FLOAT = 12;
  public static final int OCBR = 5;
  public static final int EOF = 0;
  public static final int MAIN = 2;
  public static final int GE = 24;
  public static final int CONST = 25;
  public static final int error = 1;
  public static final int EQ = 21;
  public static final int CCBR = 6;
  public static final int CBR = 4;
  public static final int BOOL = 13;
  public static final int REDO = 16;
  public static final int NEQ = 22;
}

