
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Dec 07 22:18:22 CET 2024
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 17;
  public static final int LS = 18;
  public static final int OR = 16;
  public static final int INT = 9;
  public static final int CHAR = 10;
  public static final int LOOP = 14;
  public static final int INTCONST = 25;
  public static final int ID = 24;
  public static final int LE = 19;
  public static final int GR = 22;
  public static final int OBR = 3;
  public static final int ASS = 13;
  public static final int SEMIC = 7;
  public static final int COMMA = 8;
  public static final int FLOAT = 11;
  public static final int OCBR = 5;
  public static final int EOF = 0;
  public static final int CHARCONST = 27;
  public static final int MAIN = 2;
  public static final int GE = 23;
  public static final int error = 1;
  public static final int EQ = 20;
  public static final int CCBR = 6;
  public static final int CBR = 4;
  public static final int BOOL = 12;
  public static final int REDO = 15;
  public static final int FLOATCONST = 26;
  public static final int NEQ = 21;
  public static final int BOOLCONST = 28;
}

